version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: dbsql
      WORDPRESS_DB_NAME: truyenchu
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 123456
    volumes:
      - ./wp-content:/var/www/html/wp-content

  dbsql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: truyenchu
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
